
name: pull-request-actions
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
      - name: Install and build
        run: |
          npm install 
          npm run build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: dist/
          retention-days: 5